/**
 * The Markdown half of the geometric joint audit (geo-joints.mjs writes the
 * JSON and calls this). Hand-written findings live in NOTES below so a re-run
 * does not lose them.
 */

const LIMB = ['elbow', 'wrist', 'knee', 'ankle'];
const WEAK = ['shoulder', 'hip'];
const f1 = (x) => (x === null || x === undefined || Number.isNaN(x) ? '–' : (+x).toFixed(1));
const p3 = (p) => (p ? p.map((x) => x.toFixed(3)).join(', ') : '–');

/** where the seam and the geometry part ways, and why — read off the drawings, per model */
export const NOTES = {
  din: 'Elbows: the arm fitted as two straight bones bends 18° where the vambrace meets the upper arm, and the section pinches at the same place; geometry puts the elbow 3–4.5 cm above the rig and on the limb\'s centre line, where the rig\'s sits 5.7 cm in front of it. The seam is 0.6 cm from the rig in height — it inherits it — but agrees with geometry in depth (behind the rig). Knees: the thinnest section and the thinnest core between thigh and calf coincide at 0.60 m, the lower middle of the knee pad (which spans ~0.52–0.71 m): 6 cm below the rig\'s knee and 2 cm below the seam\'s. Ankles: the instep crease is 2 cm below the rig\'s ankle, level with the boot\'s ankle disc, and 4.5 cm outboard — the rig\'s ankle sits at the inner edge of the boot, and the seam agrees with geometry on that (3 cm). Wrists: within 4 cm of rig and seam.',
  duelist: 'The duster is an open shell and the opening removes it completely, so the legs are measured bare: knees from a clean constriction 3 cm above the rig (the rig is fine), while the seam is dragged 13 cm down and out by the coat weighted to the thighs — the one place the seam is plainly wrong and geometry plainly right. Ankles: within 2.5 cm of the rig. Wrists: the cuff ends and the hand flattens 8 cm above the rig\'s wrist, which sits in the palm (the seam, 2.6 cm from the rig, follows it). Elbows: the sleeve\'s centre line bends forward 20° at 1.22 m, 10 cm above the rig\'s elbow and 6 cm behind it; only the bend fired (no constriction under the sleeve), so this is the largest and least supported move — check it in the workbench before trusting it.',
  ventress: 'Her rig is the worst of the six: elbows float beside the arm and the wrists sit in the palms. Geometry puts the wrist at the bottom of the gauntlet, where the section flattens into the hand, 11 cm above the rig\'s, and the elbow where the upper arm meets the gauntlet\'s flare (bend and constriction agree), 13 cm above the rig and 12 cm from the seam — which follows the rig along the limb. The skirt is removed by the opening; knees and ankles move 5–7 cm outward onto the legs\' centre lines (the seam agrees on the ankles, 4 cm).',
  paz: 'Bulky armour but clean shapes: geometry agrees with the seam within 1.3–4.6 cm on every limb joint. The rig\'s knees sit 7 cm behind the knee\'s centre line (the seam says the same, 3 cm from geometry) and its elbows 4 cm low; elbow confidence is middling (0.44) because the bend is shallow (9°).',
  tusken: 'The robe is torn cloth fused to the legs, so the section area reads the hem, not the knee; the core-thickness cue alone finds a knee within 3 cm of rig and seam, at low confidence (0.13). Wrists: the wrappings end and the hand begins 10 cm above the rig\'s wrist (the rig\'s is in the palm; the seam, 3.8 cm from the rig, follows it). Elbows: bend and constriction agree 8 cm above the rig and 7 cm behind it.',
  stormtrooper: 'Knees agree to 0.6 cm with the rig and 2 cm with the seam: the gap between thigh and shin plates is a clean constriction. Wrists: the glove\'s cuff ends and the hand flattens 8.5 cm above the rig\'s wrist, which is at the knuckles. Elbows: the arm bends 16° at the top of the forearm plate, 9–10 cm above the rig and seam (which agree with each other, 2.3 cm) — the forearm the rig implies would be about 0.09 H long against an anatomical 0.146 H, and the geometric one matches the anatomical length.',
};

export function report(json) {
  const models = json.models;
  const L = [];
  L.push('# Geometric joint audit', '');
  L.push('Generated by `tools/asset-pipeline/geo-joints.mjs` (data in `geo-joints.json`); do not edit by hand — the findings per model live in `geo-report.mjs`. No .glb is modified by it.', '');
  L.push('Every authored character in its bind pose at its fitted height, with each limb joint estimated from the **volume of the mesh alone** — no bones, no skin weights — and compared with the rig\'s joint and, where the rig audit (`rig-joints.json`) was at hand, with the skin-weight seam estimate. Frame: metres, x = the character\'s left, y up, z forward; offsets are *geometry minus rig* (or minus seam), in cm.', '');
  L.push('## How the estimate is made', '');
  L.push('1. **Volume.** The triangles are voxelised at 1 cm and the outside flood-filled; whatever the fill cannot reach is solid. The sculpts are single closed shells, so this is exact up to a voxel; an open coat, cape or robe (its hem lets the fill in) is left as a thin shell, and a morphological **opening** with a 2 cm ball removes every shell thinner than 4 cm — coats, capes, robes, straps and fingers — while leaving limbs and torso their shape.');
  L.push('2. **Segments.** The **crotch** is where the two legs\' horizontal slice components join. Each **arm** is followed, slice by slice, from where it hangs clear of the torso up to the **armpit** (where it merges) and down to the hand; above the armpit it is cut from the torso by the vertical plane through its inner edge.');
  L.push('3. **Centre lines and profiles.** Each limb\'s voxels are ordered by geodesic distance from its root; the limb is then cut square to the resulting centre line every centimetre. Each cut gives a centroid, a *core* centroid (weighted by depth below the surface, so a flap of robe barely moves it), its area, its largest inscribed radius and its principal widths.');
  L.push('4. **Cues**, pooled across both sides (a feature both limbs show counts double, one only one side shows counts once):');
  L.push('   - *knee*: the thinnest section between thigh and calf (only where the cut is limb-shaped), the thinnest core (inscribed radius), and a bend in the centre line (standing legs rarely have one);');
  L.push('   - *ankle*: the **instep crease** — a two-segment fit of the front surface where the near-vertical shin turns into the sloping top of the foot — and the top of the foot\'s flare (the section lengthening forward), placed on the shin\'s centre line carried down;');
  L.push('   - *wrist*: where the section **flattens into the hand** (aspect ratio 0.25 above the forearm\'s), and the thinnest cut just above it;');
  L.push('   - *elbow*: the arm fitted as **two straight bones** from the armpit to the wrist (the split with the best fit, and its angle), and the constriction between upper arm and forearm (weighted lower: it is often a gap between armour pieces);');
  L.push('   - *shoulder* and *hip* (weak): the upper arm\'s axis carried up to the top of the shoulder less one arm radius, pulled toward the centroid of the shoulder cap; the thigh\'s axis carried up to 0.04 H above the crotch or the pelvis\'s widest point.');
  L.push('5. **Priors as search windows only**: knee 0.22–0.40 H above the floor (centred 0.29 H), ankle about 0.05 H, wrist 0.05–0.18 H from the fingertip (centred 0.108 H), elbow a forearm (1.35 hand-lengths) above the wrist found. A cue far from its prior counts for less; a joint with no cue falls back on the prior with confidence 0.1.');
  L.push('6. **Confidence** (0–1): the combined weight of the cues that agree within 4 cm, less the weight of those that disagree, less any left/right mismatch of the final points. Cue (c) of the brief — boundaries between separate mesh pieces — never fires: every sculpt here is one connected, closed shell (armour, boots and gauntlets are sculpted onto it, not separate pieces).', '');
  L.push('**How far to trust it.** Knees on bare, tight-clad or cleanly plated legs and wrists on anything with a hand read well: the cues agree and both sides match. Ankles read the instep crease, which on a boot is the boot\'s crease — within a few cm of the joint, and a consistent reading across models. Elbows are the least certain limb joint: the bend is real in every bind pose here, but a sleeve or plate can put its best split a few cm off the anatomical joint. Shoulders and hips are hidden inside the torso and are given only for completeness (confidence ≤ 0.3); do not move them from this.', '');

  // ---- summary ----
  L.push('## Summary', '');
  L.push('Height offsets (geometry minus rig, cm, mean of both sides; + = geometry higher) and the full 3-D offset, with confidence. ✓ = geometry and seam agree within 3 cm.', '');
  L.push('| model | H | elbow Δy / |Δ| (conf) | wrist | knee | ankle |');
  L.push('|---|---|---|---|---|---|');
  for (const [id, m] of Object.entries(models)) {
    if (m.error) { L.push(`| ${id} | ${m.height} | failed: ${m.error} | | | |`); continue; }
    const cell = (j) => {
      const a = m.joints[`${j}.L`], b = m.joints[`${j}.R`];
      const dy = ((a.d?.[1] ?? 0) + (b.d?.[1] ?? 0)) / 2;
      const off = ((a.offsetCm ?? 0) + (b.offsetCm ?? 0)) / 2;
      const conf = Math.min(a.conf, b.conf);
      const agree = a.seamOffsetCm !== null && b.seamOffsetCm !== null && a.seamOffsetCm < 3 && b.seamOffsetCm < 3 ? ' ✓' : '';
      return `${dy >= 0 ? '+' : ''}${f1(dy)} / ${f1(off)} (${conf.toFixed(2)})${agree}`;
    };
    L.push(`| ${id} | ${m.height} | ${LIMB.map(cell).join(' | ')} |`);
  }
  L.push('');

  // ---- agreement ----
  L.push('## Where geometry and the seam agree, and where not', '');
  const rows = [];
  let agree = 0, agree5 = 0, total = 0, inherit = 0, farBoth = 0;
  for (const m of Object.values(models)) {
    if (m.error) continue;
    for (const j of LIMB) for (const s of ['L', 'R']) {
      const e = m.joints[`${j}.${s}`];
      if (e.seamOffsetCm === null) continue;
      total++;
      if (e.seamOffsetCm < 5) agree5++;
      if (e.seamOffsetCm < 3) agree++;
      else if (e.rigSeamCm < 3) inherit++;
      else farBoth++;
    }
  }
  L.push(`Over all ${total} limb joints with a seam estimate: **${agree}** agree with geometry within 3 cm (${agree5} within 5 cm); **${inherit}** disagree while the seam sits within 3 cm of the rig — the seam inheriting the rig's placement along the limb, which is exactly the weakness the rig audit warned about; **${farBoth}** disagree with both. The pattern across models is consistent: geometry and seam mostly agree *across* the limb (both put the joint inside it, where the rig often does not) and disagree *along* it — most of all at the wrists and elbows, where the rig's wrist sits in the palm and its elbow low on the forearm and the seam follows. Where the seam is far from both, a coat, robe or plate weighted to the limb has dragged it (Cad Bane's knees, the Pyke capo), or the geometry is reading a sleeve or plate edge — the models whose confidence is low below.`, '');
  for (const [id, note] of Object.entries(NOTES)) if (models[id] && !models[id].error) rows.push(`- **${id}** — ${note}`);
  L.push(...rows, '');

  L.push('## Re-rigging from it', '');
  L.push('`node tools/asset-pipeline/rerig.mjs <id> --source=geo [--min-confidence=0.6] [--min-offset=2]` moves the limb joints that are confident on both sides (and at least 2 cm from the rig) to the mirrored geometric estimate and writes `public/models/<id>_rerig_geo.glb`; the workbench shows `din_rerig_geo` and `duelist_rerig_geo` beside the originals (Compare), and its **Geometric joints** toggle draws this audit on any character, following the pose (green geometry, blue seam, red rig), with the volume stand-in on request.', '');
  L.push('**Recommendation.** Wrists first: on most models the rig\'s wrist sits in the palm, the geometric one is where the hand starts, and the two cues (flattening, constriction) agree — move them wherever confidence ≥ 0.7. Knees and ankles next, but mostly *across* the limb (onto the centre line) — the heights move a few cm and are the less certain part. Elbows: the geometry is consistent (a clear bend in every A-pose, and a forearm of anatomical length), but the moves are large (10–15 cm on many models) and a bend in a sleeve can sit a few cm off the joint — accept them per model after looking at aim, melee and landing in the workbench, not wholesale. Do not move shoulders or hips from this audit. Moving a wrist moves every hand-relative grip on that hand, which then needs re-placing.', '');

  // ---- per model ----
  for (const [id, m] of Object.entries(models)) {
    L.push(`## ${id}`, '');
    if (m.error) { L.push(`Failed: ${m.error}`, ''); continue; }
    L.push(`Height ${m.height} m; crotch at ${m.crotchY} m; armpits at ${m.armpitY.L} / ${m.armpitY.R} m; ${m.triangles} triangles.`, '');
    L.push('| joint | conf | geometry | rig | seam | geo − rig | Δy | geo − seam | rig − seam | cues that agree |');
    L.push('|---|---|---|---|---|---|---|---|---|---|');
    for (const j of [...LIMB, ...WEAK]) for (const s of ['L', 'R']) {
      const e = m.joints[`${j}.${s}`];
      L.push(`| ${j}.${s} | ${e.conf.toFixed(2)} | ${p3(e.est)} | ${p3(e.at)} | ${p3(e.seam)} | ${f1(e.offsetCm)} | ${f1(e.d?.[1])} | ${f1(e.seamOffsetCm)} | ${f1(e.rigSeamCm)} | ${(e.used?.length ? e.used : e.cues.map((c) => c.name)).join('; ') || 'prior only'} |`);
    }
    L.push('');
  }
  return `${L.join('\n')}\n`;
}
